### PR TITLE
refactor: enforce Google Typescript Style

### PR DESCRIPTION
**Pull request by cakekindel**

### CODE REVIEW

**Comment by cakekindel** [comment]
@desertviper how would you feel about transitioning to a code format more in line with the general TS community?

This PR is based on [Google's typescript style](https://github.com/google/gts) and adopting it is super easy

**Comment by desertviper** [comment]
100% thumbs up on this. I'll review and approve the pull request as soon as I can.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by cakekindel** [comment]
awesome, definitely don't worry about going through each file since these are just style changes; as long as the gist of the new style looks good to you then we're golden

**Comment by cakekindel** [comment]
oops

**Pull request merged**
